
export const REQUEST_USER_ACTION = 'REQUEST_USER_ACTION'; 

export const INJECT_SUCCESS = 'INJECT_USER_SUCCESS';
export const INJECT_FAILURE = 'INJECT_USER_FAILURE';
export const LOGOUT = 'LOGOUT_USER';

export const REQUEST_GIST_ACTION = 'REQUEST_GIST_ACTION'; 

export const GETALL_SUCCESS = "GET_ALL_GISTS_SUCCESS";
export const GETALL_FAILURE = "GET_ALL_GISTS_FAILURE";
export const GETONE_SUCCESS = "GET_SINGLE_GIST_SUCCESS";
export const GETONE_FAILURE = "GET_SINGLE_GIST_FAILURE";
export const RESET_GIST = "RESET_SINGLE_GIST";
export const CREATE_SUCCESS = "CREATE_GISTS_SUCCESS";
export const CREATE_FAILURE = "CREATE_GISTS_FAILURE";
export const UPDATE_SUCCESS = "UPDATE_GISTS_SUCCESS";
export const UPDATE_FAILURE = "UPDATE_GISTS_FAILURE";
export const DELETE_SUCCESS = "DELETE_GISTS_SUCCESS";
export const DELETE_FAILURE = "DELETE_GISTS_FAILURE";

export const TOAST_DASH_MESSAGE = 'TOAST_DASH_MESSAGE';
export const TOAST_DASH_CLEAR  = 'TOAST_DASH_CLEAR';